//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_09_Lombard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsDatepeyment
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> datepeyment_end { get; set; }
        public Nullable<System.DateTime> datepetment_fact { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
        public virtual ProductsStatus ProductsStatus { get; set; }
    }
}
