//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_09_Lombard.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsDatepeyment = new HashSet<ProductsDatepeyment>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> type_id { get; set; }
        public string date { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<double> deposit_amount { get; set; }
        public Nullable<double> redemtion_amount { get; set; }
        public Nullable<int> client_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ProductsType ProductsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsDatepeyment> ProductsDatepeyment { get; set; }
    }
}
